language: node_js
node_js:
  - "8"
  - "9"
  - "12"
  - "13"
  - "14"
addons:
  chrome: stable

branchs:
  only:
    - main
cache:
  directories:
    - node_modules
install:
  - yarn install
scripts:
  - yarn test

